version: '3.8'

services:

  kafka:
    container_name: kafka_container
    image: bitnami/kafka:latest
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100 #$CF_HOST_IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_MESSAGE_MAX_BYTES: 2000000
#      KAFKA_CREATE_TOPICS: "Topic1:1:1"
#      ALLOW_PLAINTEXT_LISTENER: true
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
#    links:
#      - zookeeper:zk
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper_container
    image: bitnami/zookeeper:latest
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami

  akhq:
    container_name: akhq_container
    image: tchiotludo/akhq
    restart: always
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: 'kafka:9092'
    ports:
      - "8081:8080"
    links:
      - kafka

#  kafka-sender:
#    container_name: kafka-sender-app
#    build: .
#    restart: always
#    ports:
#      - "8080:8080"

volumes:
  kafka_data:
  zookeeper_data:
